name: flutter_master
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.18.1

  # Functional Extensions & Methods
  dartz: ^0.10.1

  # Networking
  dio: ^5.1.2
  freezed_annotation: 2.2.0
  json_annotation: 4.8.1
  retrofit: 4.0.1

  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.1

  # Routing
  auto_route: 7.8.3
  firebase_core: ^2.21.0

  firebase_database: ^10.0.9
  # cloud_firestore: ^4.3.1
  flutter_svg: ^2.0.8
  gap: ^3.0.1
  google_fonts: ^5.1.0
  cached_network_image: ^3.3.1
  change_app_package_name: ^1.1.0
  connectivity_plus: ^5.0.2
  cloud_firestore: ^4.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6

  firebase_storage: ^11.0.10

  flutter_gen_runner: 5.3.2
  retrofit_generator: ^7.0.1
  riverpod_generator: ^2.2.3
  json_serializable: 6.7.1
  freezed: 2.3.4
  custom_lint: 0.4.0
  riverpod_lint: 1.3.2
  auto_route_generator: 7.1.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: 'assets/icons/logo.png'
  android: 'launcher_icon'
  ios: true
  # android: true

flutter:
  uses-material-design: true
  assets:
    # - assets/svg/
    - assets/icons/
  # - assets/json/

flutter_gen:
  output: lib/presentation/shared/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
